steps:
  - name: 'adoptopenjdk:11-jdk-hotspot'
    args: ['./gradlew', 'bootJar']
    env:
      - 'GRADLE_OPTS="-Dorg.gradle.daemon=false"'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sag-resources-a696d780/github.com/joeyslalom/neowise', '.']
images: ['gcr.io/sag-resources-a696d780/github.com/joeyslalom/neowise']
